server:
  port: 8090

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  freemarker:
    template-loader-path: classpath:/generator
    suffix: .ftl
    settings:
      default_encoding: UTF-8
      number_format: computer
  datasource:
    hikari:
      initialization-fail-timeout: 0
    url: jdbc:mysql://localhost:3306/code_generator?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
